import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Generated by Next.js
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Dependencies
    'node_modules/**',
    // Test coverage
    'coverage/**',
    // TypeScript build info
    '**/*.tsbuildinfo',
    // Vercel
    '.vercel/**',
    // Generated by shadcn CLI
    'src/components/ui/**',
    // Generated by Supabase CLI (supabase gen types typescript)
    'src/types/database.types.ts',
  ]),
]);

export default eslintConfig;
